/** Same [Chinese, English] catalogue convention as the rest of the product. */
export const tourLabels: Record<string, [string, string]> = {
  tourHelp: ['帮助与引导', 'Help & guided tours'], tourWelcome: ['把四个部门的表，变成能核对的结果', 'Four departments. One traceable picture.'],
  tourWelcomeBody: ['用一个虚构商砼公司的月度案例，亲手整合部门表、查看差异并追溯原件。无需准备文件，也不调用付费模型。', 'Work through a fictional concrete supplier’s monthly files. Inspect the combined table, investigate a discrepancy and trace a value to its source. No files to prepare. No paid model calls.'],
  tourWelcomeResult: ['最后你会下载一份带待确认项的总表，并保存一个可以重开的笔记本。', 'Leave with a downloaded workbook and a saved notebook you can reopen. Open questions stay visible.'],
  tourStart: ['开始引导', 'Start guided task'], tourLater: ['稍后再说', 'Maybe later'], tourResume: ['继续引导', 'Continue tour'], tourRestart: ['重新开始', 'Restart tour'],
  tourReset: ['重置本笔记本的引导', 'Reset this notebook’s tour'], tourResetHelp: ['只清除本标签页中的引导进度，不修改笔记本、文件或审批。', 'Clears tour progress in this tab only. Your notebooks, files and decisions are kept.'],
  tourStorage: ['进度仅保存在本浏览器标签页，并按原生笔记本区分。刷新可继续；其他标签页和其他笔记本不共用完成状态。', 'Your tour progress is saved in this browser tab, separately for each notebook.'],
  tourStorageUnavailable: ['浏览器不允许保存引导进度；这次仍可完成引导，刷新后需重新开始。', 'This browser cannot save tour progress. You can still finish now; a refresh will start over.'],
  tourNext: ['下一步', 'Next'], tourBack: ['上一步', 'Back'], tourExit: ['退出引导', 'Exit tour'], tourMore: ['了解更多', 'Why this matters'],
  tourAction: ['现在请操作', 'YOUR NEXT ACTION'], tourExpected: ['完成后你会看到', 'WHAT TO EXPECT'], tourStep: ['步骤', 'Step'],
  tourWaitingAction: ['完成高亮操作后自动继续', 'Continues after the highlighted action succeeds'], tourDoneAction: ['此操作已完成；可回看说明后继续。', 'Already done. Review this explanation, then continue.'],
  tourWaiting: ['正在等真实界面就绪', 'Waiting for the workspace'], tourWaitingBody: ['目标可能正在加载或被弹窗盖住。请完成当前弹窗中的选择；失败时关闭弹窗后重试。引导不会代你提交。', 'The control may still be loading, or a dialog is covering it. Finish or close the dialog, then try again. The tour never submits anything for you.'],
  tourMissing: ['这一步暂时不可用', 'This step is not available yet'], tourMissingBody: ['控件未出现、页面无数据或权限不足。检查页面提示，然后重试定位；也可以回到入口或退出，稍后继续。', 'The control didn’t appear, the page has no data, or you don’t have access. Check the message on the page and retry, or exit and come back later.'],
  tourError: ['操作未成功', 'The action did not succeed'], tourErrorHelp: ['请按页面提示修正后重试高亮操作；未成功前不会推进。若暂时无法恢复，可退出后继续。', 'Correct the issue and retry the highlighted action. The tour stays here until it succeeds. You can exit and continue later.'],
  tourRetry: ['重试定位', 'Retry locating'], tourEntry: ['回到本步页面', 'Open this step’s view'], tourSkipped: ['已暂时跳过，任务未记为完成。', 'Paused, not completed. Continue whenever you are ready.'],
  tourFinish: ['完成引导', 'Finish tour'], tourComplete: ['你的第一份可追溯总表已准备好', 'Your first traceable workbook is ready'],
  tourCompleteBody: ['你已查看模拟案例的差异和来源、发起总表下载，并保存了笔记本。待确认项仍然需要负责人处理，这不是业务签发。', 'You checked a discrepancy and its source, downloaded the workbook and saved your notebook. The open items still need their owners; nothing has been approved.'],
  tourExplore: ['查看结果，自由探索', 'View result & explore'], tourSupplementDone: ['补充引导已读完', 'You’ve explored this module'], tourSupplementBody: ['这里只介绍了真实入口与边界，未启动研判、签发报价或对外发送。', 'You saw the real entry points and their limits. Nothing was started, approved or sent.'],
  tourResumeCore: ['继续核心任务', 'Continue core task'],
  tourCore: ['首次任务 · 整合与追溯', 'First task · combine & verify'], tourReview: ['深入了解 · 四部门研判', 'Explore · department review'], tourQuotation: ['深入了解 · 报价工作区', 'Explore · quotation workspace'],
  tourHelpCompleted: ['本引导已完成。可以重播或探索其他模块。', 'This tour is complete. Replay it or explore another module.'],
  tourIncomplete: ['任务尚未完成', 'Your task is still in progress'], tourIncompleteBody: ['有实际操作尚未成功。继续完成剩余步骤，或者退出稍后再试。', 'Some actions have not succeeded yet. Continue with the remaining steps, or exit and try later.'],
  tourSafety: ['模拟案例 · 无付费调用', 'SYNTHETIC CASE · NO MODEL CHARGES'],
  tour_sample_title: ['打开可复现的月度案例', 'Open the monthly sample'],
  tour_sample_body: ['四个部门用不同的表记录同一批项目。样例会创建一个独立笔记本，原件与结果长期保存在本机服务中。', 'Four departments record the same projects in different files. The sample opens them in a new notebook.'],
  tour_sample_action: ['点击「打开示例笔记本」。如果有未保存的编辑，先在弹窗中决定是否保存。', 'Click Open sample notebook. If you have unsaved edits, decide whether to save them in the dialog first.'],
  tour_sample_expected: ['来源区出现部门文件和月份。必须导入并保存成功，引导才会继续。', 'The four department files and their month appear under Sources.'],
  tour_sample_more: ['全部是虚构数据。重播可复用当前样例，不会自动重复导入。服务数据不等于备份，部署迁移时仍需保留数据目录。', 'All records are fictional. Replaying reuses this sample instead of importing it again. Stored data is not a backup: keep the service data folder when you move the installation.'],
  tour_master_title: ['让四份表汇成一份', 'Open the combined table'],
  tour_master_body: ['总表按项目、客户和月份对齐，不用名称相似度猜关系。', 'The combined table lines up projects, customers and months using the keys defined in the dictionary, not by guessing from similar-looking names.'],
  tour_master_action: ['点击工作室中的「跨部门总表」。', 'Click Cross-department master in Studio.'],
  tour_master_expected: ['真实计算的总表加载完成，显示行状态与待确认项。', 'The table loads, with each row’s status and any open questions.'],
  tour_result_title: ['先看完整性，再看数字', 'Read the status before the numbers'],
  tour_result_body: ['完整行表示声明的核对已通过；部分行仍有分歧。样例保留了一处客户名称差异，避免把不确定性藏起来。', 'A complete row passed the declared checks. A partial row still has a discrepancy. This sample keeps a customer-name disagreement visible.'],
  tour_result_action: ['阅读行数、待确认计数和下面的行状态，然后点下一步。', 'Read the row and open-item counts, then choose Next.'],
  tour_result_expected: ['你知道哪些结果可核对，哪些还需要业务负责人决定。', 'You can distinguish computed results from decisions still owed by a person.'],
  tour_result_more: ['规则和假设随导入批次冻结。完整不代表签发，也不代表公司已经批准了示例政策。', 'The rules and assumptions are fixed when the files are imported. A complete row has been checked; it has not been signed off.'],
  tour_issues_title: ['找出需要人决定的差异', 'Investigate an open question'],
  tour_issues_body: ['不同部门填了不同的客户名称。系统指出差异，不替负责人选择。', 'The departments used different customer names. The system flags the disagreement rather than choosing for its owner.'],
  tour_issues_action: ['展开「待确认项」，阅读涉及的字段和部门。', 'Expand Open questions and read the field and departments involved.'],
  tour_issues_expected: ['看到原始核对说明；下载时这些问题也会保留。', 'The actual check message appears. These questions are retained in the download too.'],
  tour_questionResult_title: ['把差异交给正确的人', 'Keep the disagreement visible'],
  tour_questionResult_body: ['这里列出各部门原始填写内容。名称有分歧并不意味着系统可以替人改账。', 'This shows what each department entered. BridgeFlow never edits anyone’s records to settle a mismatch.'],
  tour_questionResult_action: ['阅读展开的差异说明。核对后点下一步；这里只查看，不改原件。', 'Read the expanded check message, then choose Next. This is an inspection; the sources stay intact.'],
  tour_questionResult_expected: ['你可以说明哪个字段需要负责人确认。', 'You can identify the field that needs its owner’s decision.'],
  tour_sourceVerified_title: ['核对文件与行号', 'Verify the retained source'],
  tour_sourceVerified_body: ['文件指纹用于辨认输入版本；原件行号将总表中的值与部门文件连接起来。', 'The fingerprint identifies the input version. Original row numbers connect the value in the master to the department file.'],
  tour_sourceVerified_action: ['阅读来源信息和上方原件预览，再点下一步。如已收起，可重新展开。', 'Read the file provenance and the source preview above, then choose Next. Expand the section again if it is closed.'],
  tour_sourceVerified_expected: ['你知道依据保存在何处，而不是只依赖聊天解释。', 'You know where the evidence is kept, not just what the chat said.'],
  tour_evidence_title: ['让一个数字说清出处', 'Inspect a value’s evidence'],
  tour_evidence_body: ['数字有用的前提是能查证。单元格的依据会指出原文件、工作表和原件行。', 'A value is useful when you can verify it. Its evidence identifies the file, worksheet and original row.'],
  tour_evidence_action: ['点击高亮的总表单元格，打开它的依据。', 'Click the highlighted table cell to open its evidence.'],
  tour_evidence_expected: ['出现这一个单元格的真实来源，不是示意图。', 'The real source of this exact cell opens.'],
  tour_source_title: ['回到真正的原件', 'Follow the evidence to the source'],
  tour_source_body: ['核对部门填写了什么，才能判断公式和解释是否可靠。', 'Check what the department supplied before relying on a formula or explanation.'],
  tour_source_action: ['点击「打开原件」，到来源预览核对行号和表头。', 'Click Open original source, then compare the row number and header in the preview.'],
  tour_source_expected: ['相同批次的原件预览加载完成，显示原始行号。', 'The source from the same batch loads with original row numbers.'],
  tour_sourceDetails_title: ['确认没有看错文件', 'Confirm which file you are reading'],
  tour_sourceDetails_body: ['来源信息记录文件、批次与文件指纹。换一批数据，不会重写这一批原件。', 'Source information identifies the file, batch and fingerprint. Importing a new batch does not overwrite this source.'],
  tour_sourceDetails_action: ['展开「文件来源信息」。', 'Expand File provenance.'],
  tour_sourceDetails_expected: ['查看文件名和批次信息后，再继续导出。', 'Identify the retained file and batch before exporting.'],
  tour_download_title: ['把结果带走，连同待确认项', 'Download the result with its caveats'],
  tour_download_body: ['下载工作簿包含总表、待确认项和口径假设，方便交给负责人核对。', 'The workbook includes the master table, open questions and policy assumptions for the owners to review.'],
  tour_download_action: ['点击「下载总表 xlsx」，并检查浏览器的下载列表。', 'Click Download master xlsx and check your browser’s downloads.'],
  tour_download_expected: ['工作簿生成并发起下载后才继续。浏览器是否最终保存文件需你确认。', 'The tour continues once the download starts. Check your browser for the file.'],
  tour_named_title: ['给这次工作起个好找的名字', 'Name this piece of work'],
  tour_named_body: ['清楚的名称让你和接手的人知道，这本笔记本记录了什么。', 'A clear name helps you and the next person recognise this notebook.'],
  tour_named_action: ['在顶部名称框中输入一个新名称，然后移开焦点。', 'Enter a new name in the title field, then leave the field.'],
  tour_named_expected: ['名称显示为未保存。下一步会明确保存，而不是假定自动保存。', 'The title shows as unsaved. You’ll save it in the next step.'],
  tour_saved_title: ['保存，方便下次回来', 'Save it for your next visit'],
  tour_saved_body: ['文件与计算结果已经保留；保存笔记本把名称和批次绑定，便于从笔记本列表重开。', 'Your files and results are already kept. Saving links this name to the batch so you can reopen it from Notebooks.'],
  tour_saved_action: ['点击顶部「保存」。', 'Click Save notebook in the top bar.'],
  tour_saved_expected: ['服务器确认保存后，引导才会显示完成。失败时请重试保存。', 'The tour finishes once the save is confirmed. If it fails, try Save again.'],
  tour_reviewIntro_title: ['何时让四个部门一起研判', 'When to ask the department agents'],
  tour_reviewIntro_body: ['这里可以发起真实模型调用，可能计费。模型解释已声明指标，不能自行签发业务结果。', 'Starting a review calls the AI model, which may cost money. The agents explain the figures; they can’t sign off business results.'],
  tour_reviewIntro_action: ['本补充引导只介绍入口。阅读后点下一步，不必启动研判。', 'This short tour explains the entry. Choose Next without starting a review.'],
  tour_reviewIntro_expected: ['你知道计费边界和人工责任。要真正运行，请先退出引导并确认模型配置与预算。', 'Before running it for real, exit the tour and check the model setup and budget.'],
  tour_reviewState_title: ['区别处理中、成功与部分失败', 'Distinguish progress from success'],
  tour_reviewState_body: ['状态来自实际工具与子会话。某个部门失败时，报告保留 partial，不会替它补一个结论。', 'Status comes from the actual agent runs. If a department fails, the report is marked partial and nothing is made up for it.'],
  tour_reviewState_action: ['找到业务状态入口；阅读后点下一步。', 'Locate Business state, then choose Next.'],
  tour_reviewState_expected: ['等待处理不等于完成；人工意见也不会把失败报告变成已批准。', 'Waiting isn’t finished, and a human note doesn’t turn a failed report into an approval.'],
  tour_reviewHistory_title: ['从保存的报告核对结果', 'Return to the saved report'],
  tour_reviewHistory_body: ['真正完成的研判会出现在产物列表。普通聊天回复不是已校验报告。', 'A finished review appears in the artifacts list. An ordinary chat reply is not a validated report.'],
  tour_reviewHistory_action: ['查看产物列表。为空时表示这里还没有保存的研判报告。', 'Inspect the artifacts area. An empty list means no review report has been saved here yet.'],
  tour_reviewHistory_expected: ['本引导不会创建报告，也不把空列表当作成功。', 'This tour creates no report and does not treat an empty list as success.'],
  tour_quoteOpen_title: ['打开报价声明', 'Open the quotation declaration'],
  tour_quoteOpen_body: ['报价工作区展示需要哪些事实、由谁提供和如何计算。', 'The quotation workspace shows the required facts, their owners and declared calculations.'],
  tour_quoteOpen_action: ['点击「报价工作区」。', 'Click Quotation workspace.'],
  tour_quoteOpen_expected: ['看到当前声明或明确的未配置提示。', 'The current declaration or an explicit unconfigured state appears.'],
  tour_quoteScope_title: ['缺依据，就先不报价', 'Missing evidence means no quote yet'],
  tour_quoteScope_body: ['这里不是已签发报价单。原件自动抽取和对外发送尚未实现；模拟样板的算术验收不能替代业务审批。', 'This is not an issued quotation. Automatic extraction and external sending are not implemented. Arithmetic checks on synthetic samples do not replace approval.'],
  tour_quoteScope_action: ['阅读当前阶段与所需依据，再结束补充引导。', 'Read the current stage and required evidence, then finish this short tour.'],
  tour_quoteScope_expected: ['知道下一步该找谁补材料，而不是误以为已经报出价格。', 'Know whose evidence is missing, without mistaking the preview for a submitted price.'],
  masterOpenQuestions: ['待确认项', 'Open questions'], masterEvidence: ['单元格依据', 'Cell evidence'], masterOpenSource: ['打开原件', 'Open original source'], masterSelectCell: ['查看单元格依据', 'Inspect cell evidence'], masterCompleteRows: ['完整行', 'complete rows'],
}
