"""What the system decided, and how it scores against its own claims.

Two read-only surfaces for the studio:

- `GET /journal` — the decision journal: every request, its outcome, how long it took and,
  when it refused, the sentence it refused with. Recorded once in middleware, so coverage
  cannot drift away from the code.
- `GET /eval/report` — the last generated acceptance report: the golden path over three
  held-out industries, and the adversarial half (planted instructions, missing data, absent
  declarations). Generated by `python -m bridgeflow.eval --json`, never written by hand; if
  nobody has run it, this says so rather than showing a stale green.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import Annotated

from fastapi import APIRouter, Depends, Query

from bridgeflow import journal
from bridgeflow.eval import report_path
from bridgeflow.identity import UserIdentity, require_user

router = APIRouter(tags=["observability"])


@router.get("/journal")
async def decision_journal(user: Annotated[UserIdentity | None, Depends(require_user)],
                           day: str = "", outcome: str = "", surface: str = "", batch_id: str = "",
                           limit: Annotated[int, Query(ge=1, le=500)] = 200) -> dict:
    """Decisions, newest first, with the counts above them. Ids and reasons, never rows."""
    return journal.read(day=day, outcome=outcome, surface=surface, batch_id=batch_id, limit=limit)


@router.get("/journal/runs")
async def decision_runs(user: Annotated[UserIdentity | None, Depends(require_user)],
                        day: str = "", limit: Annotated[int, Query(ge=1, le=50)] = 20) -> dict:
    """The same journal, grouped into agent runs: one model-requested call and its tree."""
    return journal.runs(day=day, limit=limit)


@router.get("/eval/report")
async def eval_report(user: Annotated[UserIdentity | None, Depends(require_user)]) -> dict:
    """The generated acceptance report, with how old it is."""
    path = report_path()
    if not path.is_file():
        return {"generated_at": "", "checks": [], "tracks": {},
                "refusal": "No acceptance report has been generated; run `python -m bridgeflow.eval --json`"}
    try:
        report = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        return {"generated_at": "", "checks": [], "tracks": {},
                "refusal": "The acceptance report could not be read; generate it again"}
    try:
        age: float | None = (datetime.now(UTC) - datetime.fromisoformat(report["generated_at"])).total_seconds()
    except (KeyError, TypeError, ValueError):
        age = None
    # A report that is a week old is not evidence about today's code; say so rather than
    # letting a green table speak for a commit it never saw.
    return report | {"age_hours": round(max(age, 0) / 3600, 1) if age is not None else None}
