from __future__ import annotations

import os
from pathlib import Path

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

# Relative settings paths are anchored at the portal/ directory.
PORTAL_ROOT = Path(__file__).resolve().parents[2]


def _default_dsh_token_file() -> str:
    """start_web.py captures dsh web's per-boot launch token into DSH_HOME
    (see scripts/start_web.py). Empty without DSH_HOME: /enter stays off."""
    dsh_home = os.environ.get("DSH_HOME", "")
    return str(Path(dsh_home) / ".web-launch-token") if dsh_home else ""


class Settings(BaseSettings):
    """Runtime configuration, read from the process environment only.

    Deliberately no env_file: these credentials decide who can sign in and what
    the portal's signatures mean, so they follow the same boundary as DSH_* —
    exported by the launching shell (env.sh), never carried by a file in the repo.
    """

    model_config = SettingsConfigDict(env_prefix="PORTAL_", extra="ignore")

    # Feishu self-built app with web-login enabled. May be the same app the
    # BridgeFlow backend uses for Drive shortcuts; the scopes differ.
    feishu_app_id: str = ""
    feishu_app_secret: str = ""
    feishu_base_url: str = "https://open.feishu.cn"

    # Ed25519 private key PEM signing app tokens. Generate with:
    #   python -m portal_app.keygen <path>   — outside the repository.
    key_path: str = ""
    # HMAC secret sealing the login state and the session cookie.
    session_secret: str = ""

    # This portal as the outside world reaches it; also the JWT issuer claim.
    external_base_url: str = "http://127.0.0.1:8100"
    apps_path: str = str(PORTAL_ROOT / "apps.yaml")

    session_ttl_seconds: int = 12 * 3600
    app_token_ttl_seconds: int = 900
    # True behind HTTPS; False only for localhost development.
    cookie_secure: bool = False
    # Set to the parent domain (".example.com") when the main site must read the
    # session too — the reverse proxy's forward_auth calls /verify with it.
    # Empty = host-only cookie on the portal host (local development).
    cookie_domain: str = ""

    # File holding dsh web's current launch token, written by start_web.py.
    # /enter 502s while it is missing (dsh web still booting or token capture off).
    dsh_token_file: str = Field(default_factory=_default_dsh_token_file)

    # Where /verify asks whether this person may reach the agent console
    # (the backend's /identity/console-access). Empty = the gate is OFF and
    # /verify answers the login question alone, exactly as before — the same
    # off-by-default posture the backend uses for PORTAL_BASE_URL. Turning it on
    # is a deployment step, because a role nobody declared yet locks everyone out.
    console_check_url: str = ""
    # How long an allow/deny answer is reused. The backend caches Feishu
    # membership for minutes; this only keeps /verify from asking on every
    # single request. Failures are never cached.
    console_check_ttl_seconds: int = 60

    # Seat fleet (docs/35): a fixed capacity of generic console instances,
    # claimed first-come-first-served by authorized people. Empty seats_path =
    # single-console behaviour, unchanged. seats.yaml declares the fleet
    # (name/port/home, no person); the assignment state lives in the
    # untracked seat_assignments file the portal rewrites on every claim.
    seats_path: str = ""
    # Parent domain the seat subdomains hang off: <seat>.console.<domain>.
    seat_base_domain: str = ""
    # Where sub→seat claims persist (instance state, untracked). Required when
    # seats_path is set; generated by scripts/provision_seat.sh --init.
    seat_assignments_path: str = ""

    host: str = "127.0.0.1"
    port: int = 8100

    @property
    def callback_uri(self) -> str:
        return f"{self.external_base_url}/callback"


settings = Settings()
