"""Generate the English sample set (data/demo_en/) from the Chinese originals.

The public demo is judged in English, but the samples are the business's own Chinese
templates. Rather than keep a second hand-edited copy that drifts, this script translates
the originals mechanically, and the originals stay the single source:

- every number, row, column order and planted problem is copied unchanged, so the English
  set must produce the same master table, open items and review checks (a test pins it);
- the words come from one glossary: `data/company_templates/labels.en.yaml` (the English
  names the interface already shows) plus `data/demo_en/glossary.yaml` for data values and
  the few places a sample needs a different word. A missing word is an error, never a guess;
- a department-prefixed master key (`财务_期初金额`) is composed from its parts
  ("Finance · Opening balance"), so the glossary never lists it twice.

Two rules come from how imports read files, not from language:

- the integration declaration matches headers exactly as written, so it gets the translated
  header; the field dictionary matches the sanitizer's snake-cased key (`Customer name` →
  `customer_name`), so a dictionary entry naming a header gets that key;
- two words may not translate to one, and two headers may not sanitize to one key: either
  would silently merge columns.

    python scripts/make_english_samples.py           # regenerate data/demo_en/
    python scripts/make_english_samples.py --check   # fail if data/demo_en/ is stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

import openpyxl
import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/demo_en"
LABELS = ROOT / "data/company_templates/labels.en.yaml"
GLOSSARY = OUT / "glossary.yaml"

YAML_FILES = {
    "data/company_templates/integration.yaml": "company_templates/integration.yaml",
    "data/mock_business/demo/dictionary.yaml": "demo/dictionary.yaml",
    "data/mock_business/cases/cases.yaml": "cases/cases.yaml",
    "data/discovery_demo/sample-project.yaml": "discovery_demo/sample-project.yaml",
    "data/discovery_demo/scoring-policy.yaml": "discovery_demo/scoring-policy.yaml",
    "data/discovery_demo/decision-policy.yaml": "discovery_demo/decision-policy.yaml",
    "data/workflow_demo/catalogue.yaml": "workflow_demo/catalogue.yaml",
    "data/workflow_demo/sample-submissions.yaml": "workflow_demo/sample-submissions.yaml",
}
XLSX_DIRS = {
    "data/mock_business/demo": "demo",
    "data/mock_business/cases": "cases",
}
TEMPLATES = ("finance", "marketing", "production", "procurement", "master")
# Repository paths inside the declarations, pointed at the English copies.
PATHS = [("data/mock_business/demo", "data/demo_en/demo"), ("data/mock_business/cases", "data/demo_en/cases")]
# Not translated (it is the business's own Chinese dictionary sheet, read by no import):
# the English declaration names the original it was transcribed from.
KEPT_ORIGINALS = {("company_templates/integration.yaml", "source_dictionary"):
                  "../../company_templates/source/dictionary-v2.xlsx"}
# The files the retained guided-tour case is pinned to, as in data/mock_business/demo/manifest.json.
MANIFEST_FILES = ["demo/finance.xlsx", "demo/marketing.xlsx", "demo/procurement.xlsx", "demo/production.xlsx",
                  "demo/dictionary.yaml", "company_templates/integration.yaml",
                  *(f"company_templates/source/{name}-v2.xlsx" for name in TEMPLATES)]

CJK = re.compile(r"[　-〿一-鿿＀-￯]")
HEADER_NOISE = re.compile(r"[\W_]+")  # the sanitizer's own rule (agents/sanitizer.py)
PREFIXED = re.compile(r"^(生产|物资|财务|市场)_(.+)$")
HEADER = "# Generated by scripts/make_english_samples.py from {source}. Do not edit: change the\n" \
         "# original or data/demo_en/glossary.yaml and regenerate.\n"


def sanitize(header: str) -> str:
    return HEADER_NOISE.sub("_", header.strip().lower()).strip("_")


class Translator:
    def __init__(self) -> None:
        labels = yaml.safe_load(LABELS.read_text(encoding="utf-8")) or {}
        extra = yaml.safe_load(GLOSSARY.read_text(encoding="utf-8")) or {}
        self.words: dict[str, str] = {**(labels.get("names") or {}), **(labels.get("texts") or {}),
                                      **(extra.get("terms") or {})}
        self.words = {str(k): str(v) for k, v in self.words.items()}
        self.same_english = set(extra.get("same_english") or [])
        self.used: dict[str, str] = {}
        self.missing: set[str] = set()
        self.merged: list[str] = []

    def __call__(self, text: str) -> str:
        if not CJK.search(text):
            return text
        if text in self.words:
            english = self.words[text]
        elif (prefixed := PREFIXED.match(text)) and prefixed.group(2) in self.words:
            english = f"{self.words[prefixed.group(1)]} · {self.words[prefixed.group(2)]}"
        else:
            self.missing.add(text)
            return text
        self.used[text] = english
        return english

    def collisions(self) -> list[str]:
        seen: dict[str, str] = {}
        clashes = []
        for chinese, english in sorted(self.used.items()):
            if english in seen and seen[english] != chinese and english not in self.same_english:
                clashes.append(f"{seen[english]!r} and {chinese!r} both become {english!r}")
            seen.setdefault(english, chinese)
        return clashes


def header_row(sheet) -> list[str]:
    for row in sheet.iter_rows(values_only=True):
        if sum(c not in (None, "") for c in row) > 1:
            return [str(c) for c in row if isinstance(c, str)]
    return []


def source_workbooks() -> list[tuple[Path, Path]]:
    pairs = [(ROOT / "data/company_templates/source" / f"{name}-v2.xlsx",
              Path("company_templates/source") / f"{name}-v2.xlsx") for name in TEMPLATES]
    for source, target in XLSX_DIRS.items():
        for path in sorted((ROOT / source).rglob("*.xlsx")):
            pairs.append((path, Path(target) / path.relative_to(ROOT / source)))
    return pairs


def translate_workbook(source: Path, target: Path, tr: Translator) -> list[str]:
    book = openpyxl.load_workbook(source)
    merged = []
    for sheet in book.worksheets:
        before = {sanitize(h) for h in header_row(sheet)}
        if CJK.search(sheet.title):
            sheet.title = tr(sheet.title)
        for row in sheet.iter_rows():
            for cell in row:
                if isinstance(cell.value, str):
                    cell.value = tr(cell.value)
                if cell.comment is not None and CJK.search(cell.comment.text):
                    cell.comment.text = tr(cell.comment.text)
        # The originals may already carry two spellings of one header; translating must not add more.
        if len({sanitize(h) for h in header_row(sheet)}) < len(before):
            merged.append(f"{target}: translated headers sanitize onto one key")
    target.parent.mkdir(parents=True, exist_ok=True)
    book.save(target)
    return merged


def translate_yaml(node: Any, tr: Translator, dictionary_keys: dict[str, str] | None, where: str, key: str = "") -> Any:
    if isinstance(node, dict):
        out: dict = {}
        for k, v in node.items():
            name = translate_yaml(k, tr, dictionary_keys, where) if isinstance(k, str) else k
            value = translate_yaml(v, tr, dictionary_keys, where, str(k))
            if name in out and out[name] != value:
                raise SystemExit(f"{where}: {k!r} translates onto an existing key {name!r} with a different value")
            out[name] = value
        return out
    if isinstance(node, list):
        return [translate_yaml(v, tr, dictionary_keys, where, key) for v in node]
    if isinstance(node, str):
        if (where, key) in KEPT_ORIGINALS:
            return KEPT_ORIGINALS[(where, key)]
        for old, new in PATHS:
            if node.startswith(old):
                return new + node[len(old):]
        if dictionary_keys is not None and node in dictionary_keys:
            return sanitize(tr(dictionary_keys[node]))
        return tr(node)
    return node


def generate(out: Path) -> Translator:
    tr = Translator()
    workbooks = source_workbooks()
    # The dictionary names sanitized headers; remember which original header each key came from.
    dictionary_keys: dict[str, str] = {}
    for source, _ in workbooks:
        for sheet in openpyxl.load_workbook(source, read_only=True).worksheets:
            for header in header_row(sheet):
                dictionary_keys.setdefault(sanitize(header), header)

    for source, target in workbooks:
        tr.merged += translate_workbook(source, out / target, tr)
    for source, target in YAML_FILES.items():
        raw = yaml.safe_load((ROOT / source).read_text(encoding="utf-8"))
        keys = dictionary_keys if target == "demo/dictionary.yaml" else None
        english = translate_yaml(raw, tr, keys, target)
        (out / target).parent.mkdir(parents=True, exist_ok=True)
        (out / target).write_text(HEADER.format(source=source) + yaml.safe_dump(
            english, allow_unicode=True, sort_keys=False, width=110), encoding="utf-8")

    original = json.loads((ROOT / "data/mock_business/demo/manifest.json").read_text(encoding="utf-8"))
    manifest = {**original,
                "classification": original["classification"] + "; English translation of the Chinese sample",
                "files": {f"data/demo_en/{name}": hashlib.sha256((out / name).read_bytes()).hexdigest()
                          for name in MANIFEST_FILES},
                "expected": translate_yaml(original["expected"], tr, None, "manifest.json")}
    (out / "demo/manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
                                            encoding="utf-8")
    return tr


def problems(out: Path, tr: Translator) -> list[str]:
    found = [f"no English for {text!r}" for text in sorted(tr.missing)]
    found += tr.collisions() + tr.merged
    for path in sorted(out.rglob("*")):
        if path.suffix in (".yaml", ".json") and path.name != "glossary.yaml" and CJK.search(path.read_text(encoding="utf-8")):
            found.append(f"{path.relative_to(out)} still has Chinese text")
        if path.suffix == ".xlsx":
            book = openpyxl.load_workbook(path, read_only=True)
            for sheet in book.worksheets:
                if any(isinstance(v, str) and CJK.search(v) for row in sheet.iter_rows(values_only=True) for v in row):
                    found.append(f"{path.relative_to(out)} still has Chinese text")
    return found


def snapshot(root: Path) -> dict[str, Any]:
    """Content, not bytes: an xlsx written twice differs in its zip timestamps."""
    state: dict[str, Any] = {}
    for path in sorted(root.rglob("*")):
        name = str(path.relative_to(root))
        if path.suffix == ".xlsx":
            book = openpyxl.load_workbook(path, read_only=True)
            state[name] = [[sheet.title, [list(r) for r in sheet.iter_rows(values_only=True)]] for sheet in book.worksheets]
        elif path.name == "manifest.json":
            state[name] = {k: v for k, v in json.loads(path.read_text(encoding="utf-8")).items() if k != "files"}
        elif path.suffix == ".yaml" and path.name not in ("glossary.yaml", "sample-set.yaml"):
            state[name] = yaml.safe_load(path.read_text(encoding="utf-8"))
    return state


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="compare with data/demo_en/ instead of writing it")
    args = parser.parse_args()
    if args.check:
        with tempfile.TemporaryDirectory() as scratch:
            fresh = Path(scratch)
            tr = generate(fresh)
            issues = problems(fresh, tr)
            if not issues and snapshot(fresh) != snapshot(OUT):
                issues.append("data/demo_en/ differs from its originals: run scripts/make_english_samples.py")
    else:
        for name in ("company_templates", "demo", "cases", "discovery_demo", "workflow_demo"):
            shutil.rmtree(OUT / name, ignore_errors=True)
        tr = generate(OUT)
        issues = problems(OUT, tr)
    for issue in issues:
        print(issue, file=sys.stderr)
    return 1 if issues else 0


if __name__ == "__main__":
    raise SystemExit(main())
